### PR TITLE
Fix Friday morning + one business day resulted in Saturday morning

### LINKED ISSUE #9: Adding one business day to Friday 9.59 is not calculated correctly
### Description
Next business day for Friday 9.59 should be Monday 09:59 but it is returned as Saturday 09:59.
```
const businessTime: BusinessTime = new BusinessTime(
    moment.utc('Friday 2021-10-30 09:59', TEST_FORMAT),
)

const added: BusinessTime = businessTime.addBusinessDays(1)
```
returns `Saturday 2021-10-30 09:59`.

Starting from Friday 10.00 addBusinessDays(1+) is calculated correctly

### Ways to reproduce
Add `["Friday 2021-10-29 09:59", 1, "Monday 2021-11-01 09:59"],` to [testAddBusinessDaysDefault](https://github.com/freetrade-io/ts-business-time/blob/master/tests/unit/BusinessTime/AddBusinessDays.test.ts#L66)

### PR DESCRIPTION
**Pull request by nikbolotin**
Fix Friday morning + one business day resulted in Saturday morning

### CODE REVIEW

File: src/constraint/BusinessTimeConstraint.ts [hunk 1]
```diff
@@ -3,3 +3,17 @@ import moment = require("moment-timezone")
...
+export interface IBusinessDayConstraint {
+    isBusinessDay(): boolean
+}
+
+export function isIBusinessDayStatic(
+    object: unknown,
+): object is IBusinessDayConstraint {
+    const businessDayConstraint = object as IBusinessDayConstraint
+    return (
+        businessDayConstraint.isBusinessDay !== undefined &&
```
Comment (rorybainfreetrade) [inline src/constraint/BusinessTimeConstraint.ts]: Minor, but this could be `typeof businessDayConstraint.isBusinessDay === 'function'` to be sure that it's ok to call

File: src/constraint/composite/AllConstraints.ts [hunk 2]
```diff
@@ -21,6 +26,15 @@ export class AllConstraints implements ICombinatorialConstraint {
         return true
     }
 
+    isBusinessDay(): boolean {
+        for (const constraint of this.constraints) {
```
Comment (rorybainfreetrade) [inline src/constraint/composite/AllConstraints.ts]: Could write as `this.constraints.every(isIBusinessDayStatic)`

File: tests/unit/BusinessTime/AddBusinessDays.test.ts [hunk 3]
```diff
@@ -69,6 +84,36 @@ describe("adding business days", () => {
             const businessTime: BusinessTime = new BusinessTime(
                 moment.utc(time, TEST_FORMAT),
             )
+            console.log("In test")
```
Comment (rorybainfreetrade) [inline tests/unit/BusinessTime/AddBusinessDays.test.ts]: Can remove the log

File: tests/unit/BusinessTime/AddBusinessDays.test.ts [hunk 4]
```diff
@@ -69,6 +84,36 @@ describe("adding business days", () => {
...
+            const businessTime: BusinessTime = new BusinessTime(
+                moment.utc(time, TEST_FORMAT),
+                moment.duration(1, "hour"),
+                [
+                    new WeekDays(),
+                    new BetweenHoursOfDay("09", "17"),
+                    new NotConstraint(new Dates("2018-05-15", "2021-10-28")),
+                ],
+            )
+            console.log("In test")
```
Comment (rorybainfreetrade) [inline tests/unit/BusinessTime/AddBusinessDays.test.ts]: Can also remove this log

File: tests/unit/BusinessTime/AddBusinessDays.test.ts [hunk 5]
```diff
@@ -51,6 +57,15 @@ describe("adding business days", () => {
         ["Friday 2018-05-18 17:00", 1.75, "Tuesday 2018-05-22 15:00"],
         ["Friday 2018-05-18 17:00", 2, "Tuesday 2018-05-22 17:00"],
         ["Friday 2018-05-18 17:00", 3, "Wednesday 2018-05-23 17:00"],
+
+        // From Friday morning
+        ["Tuesday 2021-10-19 00:00", 2, "Thursday 2021-10-21 00:00"],
+        ["Friday 2021-10-29 09:01", 1, "Monday 2021-11-01 09:01"],
+        ["Friday 2021-10-29 10:00", 1, "Monday 2021-11-01 10:00"],
+        ["Friday 2021-10-29 04:00", 1, "Monday 2021-11-01 04:00"],
+        ["Friday 2021-10-29 00:00", 1, "Monday 2021-11-01 00:00"],
```
Comment (rorybainfreetrade) [inline tests/unit/BusinessTime/AddBusinessDays.test.ts:65]: Maybe worth adding a new case to the negative values below for Monday -1 = Friday? I think it might have issues where before we called `this.add(days, 'days')` and `days` could be negative, but now we always increment by `1`

File: tests/unit/Constraint/BusinessDay.test.ts [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+    BusinessTime,
+    Dates,
+    NotConstraint,
+    WeekDays,
+} from "../../../src"
+import { TEST_FORMAT } from "../../index"
+
+describe("Checking BusinessTime", () => {
+    test.each([
+        // ["Monday 2018-05-14 04:00", true],
```
Comment (rorybainfreetrade) [inline tests/unit/Constraint/BusinessDay.test.ts]: Can we uncomment/remove these cases?

File: src/constraint/BusinessTimeConstraint.ts [hunk 7]
```diff
@@ -3,3 +3,17 @@ import moment = require("moment-timezone")
 export interface IBusinessTimeConstraint {
     isBusinessTime(time: moment.Moment): boolean
 }
+
+export interface IBusinessDayConstraint {
+    isBusinessDay(): boolean
+}
+
+export function isIBusinessDayStatic(
```
Comment (rorybainfreetrade) [inline src/constraint/BusinessTimeConstraint.ts]: JS naming conventions would usually just be `isBusinessDay` so you can remove the static part

File: src/BusinessTime.ts [hunk 8]
```diff
@@ -48,6 +51,20 @@ export class BusinessTime {
         return true
     }
 
+    isBusinessDay(): boolean {
+        for (const constraint of this.constraints) {
```
Comment (rorybainfreetrade) [inline src/BusinessTime.ts]: Minor, but may be easier to read on one line, though that's maybe subjective 😄  `this.constraints.every(constraint => isBusinessDay(constraint) && constraint.isBusinessTime(this.getMoment))`

**Review by rorybainfreetrade — COMMENTED** [review]
A few comments to remove but otherwise minor issues, nice!

File: src/constraint/BusinessTimeConstraint.ts (hunk 7 above)
Comment (nikbolotin) [reply src/constraint/BusinessTimeConstraint.ts]: I didn't want it to be mixed with isBusinessDay from BusinessTime so I wanted the name to indicate the difference. Maybe `isIBusinessDayConstraint`?

File: src/constraint/BusinessTimeConstraint.ts (hunk 1 above)
Comment (nikbolotin) [reply src/constraint/BusinessTimeConstraint.ts]: makes sense!

File: src/constraint/composite/AllConstraints.ts (hunk 2 above)
Comment (nikbolotin) [reply src/constraint/composite/AllConstraints.ts]: good point!

File: tests/unit/BusinessTime/AddBusinessDays.test.ts (hunk 5 above)
Comment (nikbolotin) [reply tests/unit/BusinessTime/AddBusinessDays.test.ts:65]: Yeah, especially because the subtraction is [not yet implemented](https://github.com/freetrade-io/ts-business-time/blob/addBusinessDay-bug/src/BusinessTime.ts#L116) :D

File: tests/unit/Constraint/BusinessDay.test.ts (hunk 6 above)
Comment (nikbolotin) [reply tests/unit/Constraint/BusinessDay.test.ts]: will do

File: tests/unit/BusinessTime/AddBusinessDays.test.ts (hunk 5 above)
Comment (nikbolotin) [reply tests/unit/BusinessTime/AddBusinessDays.test.ts:65]: added to tests/unit/BusinessTime/SubtractBusinessDays.test.ts

File: src/constraint/RangeConstraint.ts [hunk 9]
```diff
@@ -18,7 +18,7 @@ export abstract class RangeConstraint extends CombinatorialConstraint
 
         // Allow backwards order.
         if (this.min > this.max) {
-            [this.min, this.max] = [this.max, this.min]
+            ;[this.min, this.max] = [this.max, this.min]
```
Comment (aaronsheah) [inline src/constraint/RangeConstraint.ts]: typo?

**Review by aaronsheah — COMMENTED** [review]
Please bump the patch version of this package

**Review by aaronsheah — APPROVED** [review]

**Review by rorybainfreetrade — APPROVED** [review]
